version: '2.1'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: mysql:5.7
    volumes:
      # - '/datadrive/mysql:/var/lib/mysql' # for ubuntu
      - '/Users/sadikay/datadrive/ed/mysql:/var/lib/mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=email_dashboard_prod
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    healthcheck:
      test: "/etc/init.d/mysql status"
      timeout: 16s
      interval: 5s


  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/Users/sadikay/datadrive/ed/redis:/data' # for ubuntu
    ports:
      - '6379'

  web:
    depends_on:
      db:
        condition: service_healthy
    depends_on:
      - redis
    build: ./rails-dashboard
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ED_DB_USERNAME: ${MYSQL_USER}
      ED_DB_PASSWORD: ${MYSQL_PASSWORD}
      ED_DB_HOST: db
      ED_DB_NAME: email_dashboard_prod
      VIRTUAL_HOST: dashboard.${APP_DOMAIN}

  api:
    depends_on:
      db:
        condition: service_healthy
    build: ./go-api-worker
    environment:
      - GIN_MODE=release
      - ED_DB_USERNAME=${MYSQL_USER}
      - ED_DB_PASSWORD=${MYSQL_PASSWORD}
      - ED_DB_NAME=email_dashboard_prod
      - VIRTUAL_HOST=api.${APP_DOMAIN}
    links:
      - redis:redis
      - db

volumes:
  'datadrive':
